services:
  mysql:
    image: mysql:9.2
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=TopSecret
    command: --init-file /data/application/init.sql
    volumes:
        - ./database/docker/init.sql:/data/application/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate
    volumes:
        - ./database/migrations:/migrations
    command: ["-path", "/migrations", "-database", "mysql://root:TopSecret@tcp(mysql:3306)/simple_twitter", "up"]
    depends_on:
      mysql:
        condition: service_healthy